# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import oblivious_sort_pb2 as oblivious__sort__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in oblivious_sort_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ObliviousSorterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Permute = channel.unary_unary(
                '/oblivious_sort.ObliviousSorter/Permute',
                request_serializer=oblivious__sort__pb2.SortRequest.SerializeToString,
                response_deserializer=oblivious__sort__pb2.SortReply.FromString,
                _registered_method=True)
        self.GetAccessLog = channel.unary_unary(
                '/oblivious_sort.ObliviousSorter/GetAccessLog',
                request_serializer=oblivious__sort__pb2.AccessLogRequest.SerializeToString,
                response_deserializer=oblivious__sort__pb2.AccessLogReply.FromString,
                _registered_method=True)


class ObliviousSorterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Permute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccessLog(self, request, context):
        """🆕
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObliviousSorterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Permute': grpc.unary_unary_rpc_method_handler(
                    servicer.Permute,
                    request_deserializer=oblivious__sort__pb2.SortRequest.FromString,
                    response_serializer=oblivious__sort__pb2.SortReply.SerializeToString,
            ),
            'GetAccessLog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccessLog,
                    request_deserializer=oblivious__sort__pb2.AccessLogRequest.FromString,
                    response_serializer=oblivious__sort__pb2.AccessLogReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'oblivious_sort.ObliviousSorter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('oblivious_sort.ObliviousSorter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObliviousSorter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Permute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oblivious_sort.ObliviousSorter/Permute',
            oblivious__sort__pb2.SortRequest.SerializeToString,
            oblivious__sort__pb2.SortReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccessLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oblivious_sort.ObliviousSorter/GetAccessLog',
            oblivious__sort__pb2.AccessLogRequest.SerializeToString,
            oblivious__sort__pb2.AccessLogReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
