# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oblivious_sort.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'oblivious_sort.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14oblivious_sort.proto\x12\x0eoblivious_sort\"\x1c\n\x0bSortRequest\x12\r\n\x05input\x18\x01 \x03(\x05\"!\n\x10\x41\x63\x63\x65ssLogRequest\x12\r\n\x05\x63lear\x18\x01 \x01(\x08\"7\n\x0b\x41\x63\x63\x65ssEntry\x12\n\n\x02op\x18\x01 \x01(\t\x12\r\n\x05\x61rray\x18\x02 \x01(\t\x12\r\n\x05index\x18\x03 \x01(\x05\":\n\x0e\x41\x63\x63\x65ssLogReply\x12(\n\x03log\x18\x01 \x03(\x0b\x32\x1b.oblivious_sort.AccessEntry\"A\n\tSortReply\x12\x0e\n\x06output\x18\x01 \x03(\x05\x12\x10\n\x08io_count\x18\x02 \x01(\x05\x12\x12\n\ntime_taken\x18\x03 \x01(\x01\x32\xa6\x01\n\x0fObliviousSorter\x12\x41\n\x07Permute\x12\x1b.oblivious_sort.SortRequest\x1a\x19.oblivious_sort.SortReply\x12P\n\x0cGetAccessLog\x12 .oblivious_sort.AccessLogRequest\x1a\x1e.oblivious_sort.AccessLogReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oblivious_sort_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SORTREQUEST']._serialized_start=40
  _globals['_SORTREQUEST']._serialized_end=68
  _globals['_ACCESSLOGREQUEST']._serialized_start=70
  _globals['_ACCESSLOGREQUEST']._serialized_end=103
  _globals['_ACCESSENTRY']._serialized_start=105
  _globals['_ACCESSENTRY']._serialized_end=160
  _globals['_ACCESSLOGREPLY']._serialized_start=162
  _globals['_ACCESSLOGREPLY']._serialized_end=220
  _globals['_SORTREPLY']._serialized_start=222
  _globals['_SORTREPLY']._serialized_end=287
  _globals['_OBLIVIOUSSORTER']._serialized_start=290
  _globals['_OBLIVIOUSSORTER']._serialized_end=456
# @@protoc_insertion_point(module_scope)
